name: 'Repository Dispatch'
description: 'Create a repository dispatch event'
inputs:
  token:
    description: 'A repo scoped GitHub Personal Access Token'
    required: false
  repository:
    description: 'The full name of the repository to send the dispatch.'
    default: ${{ github.repository }}
  event-type:
    description: 'A custom webhook event name.'
    required: true
  client-payload:
    description: 'JSON payload with extra information about the webhook event that your action or workflow may use.'
    default: '{}'
  client-id:
    description: 'A GitHub App Client ID'
    required: false
  client-secret:
    description: 'A GitHub App Client Secret'
    required: false
  app-id:
    description: 'A GitHub App ID'
    required: false
  app-key:
    description: 'A private key assigned to the GitHub app'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'target'
  color: 'gray-dark'
